In [98]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#check for negative values in numerical data seperate it from filling null values or detecting outliers then add new col to it or remove it or make a new ds for it
cr=pd.read_csv("healthcare_dataset.csv")
cr1=cr.copy()

In [113]:
cr1.dtypes

Name                          object
Age                            int64
Gender                        object
Blood Type                    object
Medical Condition             object
Date of Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance Provider            object
Billing Amount               float64
Room Number                    int64
Admission Type                object
Discharge Date        datetime64[ns]
Medication                    object
Test Results                  object
dtype: object

In [105]:
print(cr1.duplicated().sum())
len(cr1)
cr1=cr1.drop_duplicates()

54966

In [101]:
cr1.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [106]:
cr1.loc[1,"Billing Amount"]=np.nan
cr1.loc[3,"Billing Amount"]=np.nan

In [110]:
cr1["Date of Admission"]=pd.to_datetime(cr1["Date of Admission"],format="mixed",errors="coerce")

cr1["Discharge Date"]=pd.to_datetime(cr1["Discharge Date"],format="mixed",errors="coerce")
`
cr["Date of Admission"].unique()

In [112]:
cr1["Date of Admission"].isnull().sum()

np.int64(0)

In [20]:
#outlier checking befor null filling
#befor knowning about negative refunds
# q1=cr["Billing Amount"].quantile(0.25)
# q3=cr["Billing Amount"].quantile(0.75)
# iqr=q3-q1
# lower=q1-1.5*iqr
# upper=q3+1.5*iqr
# outliers=cr[(cr["Billing Amount"]<lower)|(cr["Billing Amount"]>upper)]
# print(outliers)

Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

In [18]:
# cr["Billing Amount"]=cr.groupby("Medical Condition")["Billing Amount"].transform(lambda x:x.fillna(x.mean()))

In [21]:
# cr.isnull().sum()

# cr.dtypes

Name                          object
Age                            int64
Gender                        object
Blood Type                    object
Medical Condition             object
Date of Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance Provider            object
Billing Amount               float64
Room Number                    int64
Admission Type                object
Discharge Date        datetime64[ns]
Medication                    object
Test Results                  object
dtype: object

In [115]:
cr1["Name"]=cr1["Name"].str.strip().str.capitalize()


# col=["Name"]
# for col in colus:
#     c.appened(col.upper())
# cr.columns=c

In [118]:
cr1["Doctor"]=cr1["Doctor"].str.strip()
cr1["Hospital"]=cr1["Hospital"].str.strip()
cr1["Insurance Provider"]=cr1["Insurance Provider"].str.strip()

# cr["Test Results"].unique()

In [121]:
cr1

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,NaN,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,NaN,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [63]:
cr.isnull().sum()
cr.duplicated().sum()
cr.dtypes
cr(len)

Name                          object
Age                            int64
Gender                        object
Blood Type                    object
Medical Condition             object
Date of Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance Provider            object
Billing Amount               float64
Room Number                    int64
Admission Type                object
Discharge Date        datetime64[ns]
Medication                    object
Test Results                  object
dtype: object

In [124]:

positive_data = cr1[cr1['Billing Amount'] > 0]['Billing Amount']

Q1 = positive_data.quantile(0.25)
Q3 = positive_data.quantile(0.75)
IQR = Q3 - Q1

valid_positive = positive_data[(positive_data >= Q1 - 1.5*IQR) & (positive_data <= Q3 + 1.5*IQR)]

median = valid_positive.median()   # or mean()



cr1["Billing Amount"]=cr1["Billing Amount"].fillna(median)

In [125]:
cr1.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [130]:
print(cr1[cr1['Billing Amount'] < 0].shape)

(106, 15)

In [133]:
cr1["Transaction"]=np.where(cr1["Billing Amount"]>0,"Billing","Refund")

cr1["Transaction"].unique()

array(['Billing', 'Refund'], dtype=object)

In [138]:
# cr1.isnull().sum()
# cr1.duplicated().sum()
# cr1.dtypes

cr1

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Transaction
0,Bobby jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,Billing
1,Leslie terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,25593.094115,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,Billing
2,Danny smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,Billing
3,Andrew watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,25593.094115,450,Elective,2020-12-18,Ibuprofen,Abnormal,Billing
4,Adrienne bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,Billing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal,Billing
55496,Kyle perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal,Billing
55497,Heather wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal,Billing
55498,Jennifer jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal,Billing
55499,James garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,Billing

In [139]:
# cr.to_csv("cleaned helathacare dataset",index=False)


cr1.to_csv(r"C:\Users\s.sherinmary\OneDrive\Documents\PROJECT\healthcare_clean.csv", index=False)
# d.to_csv("cleaned_patient_data.csv", index=False)

In [72]:
# r'^\s*$'  '^\s*$'
# cr.loc[:,'Is_Suspicious'] = cr['Billing Amount'] < 0

In [75]:
# cr["Is_Suspicious"].unique()
# # cr

array([False,  True])

In [82]:
# # cr[cr["Is_Suspicious"]==True]

# cr=cr.drop(columns="Is_Suspicious")

In [96]:
# print(cr[cr["Billing Amount"]<0])

Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

In [1]:
# cr["refunds"] = cr[cr['Billing Amount'] < 0]
# billing = cr[cr['Billing_Amount'] >= 0]

In [90]:
# cr.loc["Billing Amount"]= cr[cr['Billing Amount'] >= 0]